### ISSUE TITLE
gcc-arm-none-eabi fails to build on 10.9 with Xcode 5.0.2

### ISSUE THREAD

**Issue by ghulands** [PX4/homebrew-px4#3]
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd -I. -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd/../include  -DHAVE_bfd_elf32_littlearm_vec -DHAVE_bfd_elf32_bigarm_vec -DHAVE_bfd_elf32_little_generic_vec -DHAVE_bfd_elf32_big_generic_vec  -DBINDIR='"/usr/local/Cellar/gcc-arm-none-eabi/20121016/bin"' -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/build-macosx/host-libs/zlib/include -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/build-macosx/host-libs/zlib/include -O2 -MT elf32-gen.lo -MD -MP -MF .deps/elf32-gen.Tpo -c -o elf32-gen.lo /private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd/elf32-gen.c
/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd/elflink.c:12453:9: error: variable 'l_sec_contents' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
                  if (!bfd_malloc_and_get_section (abfd, sec, &sec_contents))
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd/elflink.c:12469:9: note: uninitialized use occurs here
                  if (l_sec_contents)
                      ^~~~~~~~~~~~~~
/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd/elflink.c:12453:5: note: remove the 'if' if its condition is always false
                  if (!bfd_malloc_and_get_section (abfd, sec, &sec_contents))
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd/elflink.c:12451:44: note: initialize the variable 'l_sec_contents' to silence this warning
                  bfd_byte *sec_contents, *l_sec_contents;
                                                         ^
                                                          = NULL
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd -I. -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd/../include -DHAVE_bfd_elf32_littlearm_vec -DHAVE_bfd_elf32_bigarm_vec -DHAVE_bfd_elf32_little_generic_vec -DHAVE_bfd_elf32_big_generic_vec -DBINDIR=\"/usr/local/Cellar/gcc-arm-none-eabi/20121016/bin\" -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/build-macosx/host-libs/zlib/include -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -I/private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/build-macosx/host-libs/zlib/include -O2 -MT elf32-gen.lo -MD -MP -MF .deps/elf32-gen.Tpo -c /private/tmp/gcc-arm-none-eabi-Th0M/gcc-arm-none-eabi-4_6-2012q4-20121016/src/binutils/bfd/elf32-gen.c -o elf32-gen.o
1 error generated.
make[4]: *** [elflink.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
mv -f .deps/elf32.Tpo .deps/elf32.Plo
mv -f .deps/dwarf1.Tpo .deps/dwarf1.Plo
mv -f .deps/elf32-gen.Tpo .deps/elf32-gen.Plo
mv -f .deps/dwarf2.Tpo .deps/dwarf2.Plo
mv -f .deps/elf-eh-frame.Tpo .deps/elf-eh-frame.Plo
mv -f .deps/elf32-arm.Tpo .deps/elf32-arm.Plo
mv -f .deps/elf.Tpo .deps/elf.Plo
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-bfd] Error 2
make: *** [all] Error 2

**Comment by LorenzMeier** [comment]
This is long fixed, sorry for not closing this a long time ago. For Reference: Toolchain now is a canned binary.
