### PR TITLE
Fix kconfig-frontends compilation on Mac M1

### PR DESCRIPTION
**Pull request by nrodichenko**
kconfig-frontends fails to compile on M1 Mac (OSX 12.2.1, XCode CLT version 13.4.0.0.1.1651278267) with the following error:  `ld: symbol(s) not found for architecture x86_64`

This patch adds an ncurses dependency, which fixes the linker error above.

### CODE REVIEW

**Comment by rakmo97** [comment]
Hello! I'm having the error you mention (`ld: symbol(s) not found for architecture x86_64`). I tried installing kconfig-frontends using the change you have but I get this error:

```
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
patching file bootstrap
patching file configure.ac
patching file 'scripts/ksync.sh'
patching file 'scripts/version.sh'
patching file 'utils/Makefile.am'
1 out of 1 hunks failed--saving rejects to 'utils/Makefile.am.rej'
patching file 'utils/tweak.in'
2 out of 2 hunks failed--saving rejects to 'utils/tweak.in.rej'
```


Any idea what the issue could be?

**Comment by rakmo97** [comment]
Nevermind on my last comment.

This branch needs to be merged ASAP because it worked for me and it seems like a lot of M1 folks are having trouble! (2021 Macbook Air with M1).  This is how I got it to work (figured out by @aaronknudtson) from @nrodichenko 's branch (before it gets merged):

1. First, I setup homebrew using the instructions here: https://medium.com/mkdir-awesome/how-to-install-x86-64-homebrew-packages-on-apple-m1-macbook-54ba295230f
This sets up an `axbrew` alias for the `brew` command.

2. Then, I ran 
`axbrew tap nrodichenko/homebrew-px4`
`cd /usr/local/homebrew/Library/Taps/nrodichenko/homebrew-px4`
`git checkout patch-1`
`axbrew install px4-dev`

If the last command doesn't work, you may need to do `axbrew untap --force PX4/px4` if you had already tapped that.
I think instead of setting up `axbrew`, you can run `brew` commands as `arch -x86_64 brew [...]`, but I haven't tried it personally.

**Comment by mengchaoheng** [comment]
@rakmo97 @nrodichenko  can you help me about https://github.com/PX4/PX4-Autopilot/issues/22826
